/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;

import Business.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        Customer();
    }
    
   /* public void populateTree(){
        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
       // Add the code for draw your system structure shown by JTree
       
        model.reload();
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemAdminPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        manageCustomerPanel = new javax.swing.JPanel();
        manageCustomers = new javax.swing.JLabel();
        manageRestaurants = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manageDeliveryMan = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SystemAdminPanelRight = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        systemAdminPanel.setBackground(new java.awt.Color(0, 0, 0));
        systemAdminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCustomerPanel.setBackground(new java.awt.Color(0, 0, 0));
        manageCustomerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageCustomerPanelMousePressed(evt);
            }
        });
        manageCustomerPanel.setLayout(new java.awt.BorderLayout());

        manageCustomers.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        manageCustomers.setForeground(new java.awt.Color(0, 153, 0));
        manageCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCustomers.setText("Manage Customers");
        manageCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageCustomersMousePressed(evt);
            }
        });
        manageCustomerPanel.add(manageCustomers, java.awt.BorderLayout.CENTER);

        jPanel1.add(manageCustomerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 50));

        manageRestaurants.setBackground(new java.awt.Color(0, 0, 0));
        manageRestaurants.setPreferredSize(new java.awt.Dimension(264, 48));
        manageRestaurants.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageRestaurantsMousePressed(evt);
            }
        });
        manageRestaurants.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageRestaurants.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Manage Restaurants");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });
        manageRestaurants.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(manageRestaurants, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 50));

        manageDeliveryMan.setBackground(new java.awt.Color(0, 0, 0));
        manageDeliveryMan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                manageDeliveryManMousePressed(evt);
            }
        });
        manageDeliveryMan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageDeliveryMan.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 37, 28));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Manage Delivery Man");
        manageDeliveryMan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 217, 40));

        jPanel1.add(manageDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 280, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3501696.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 210, 170));

        systemAdminPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 840));

        SystemAdminPanelRight.setBackground(new java.awt.Color(0, 0, 0));
        SystemAdminPanelRight.setPreferredSize(new java.awt.Dimension(940, 808));
        SystemAdminPanelRight.setLayout(new java.awt.CardLayout());
        systemAdminPanel.add(SystemAdminPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -2, 1030, 840));

        add(systemAdminPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageCustomersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomersMousePressed
        Customer();
    }//GEN-LAST:event_manageCustomersMousePressed

    private void Customer() {
        // TODO add your handling code here:
        manageCustomerPanel.setBackground(new Color(255,255,255));
        manageRestaurants.setBackground(new Color(0,0,0));
        manageDeliveryMan.setBackground(new Color(0,0,0));
        userinterface.SystemAdminWorkArea.CustomeR Customer = new userinterface.SystemAdminWorkArea.CustomeR(SystemAdminPanelRight, ecosystem);
        SystemAdminPanelRight.add("Customer",Customer);
        CardLayout layout = (CardLayout) SystemAdminPanelRight.getLayout();
        layout.next(SystemAdminPanelRight);
    }

    private void manageCustomerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCustomerPanelMousePressed
        // TODO add your handling code here:
        Customer();
    }//GEN-LAST:event_manageCustomerPanelMousePressed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        Restaurant();
    }//GEN-LAST:event_jLabel5MousePressed

    private void Restaurant() {
        // TODO add your handling code here:
        manageRestaurants.setBackground(new Color(255,255,255));
        manageCustomerPanel.setBackground(new Color(0,0,0));
        manageDeliveryMan.setBackground(new Color(0,0,0));
        userinterface.SystemAdminWorkArea.RestauranT RestaUrant = new userinterface.SystemAdminWorkArea.RestauranT(SystemAdminPanelRight, ecosystem);
        SystemAdminPanelRight.add("Restaurant",RestaUrant);
        CardLayout layout = (CardLayout) SystemAdminPanelRight.getLayout();
        layout.next(SystemAdminPanelRight);
    }
 
    private void manageRestaurantsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRestaurantsMousePressed
        // TODO add your handling code here:
        Restaurant();
    }//GEN-LAST:event_manageRestaurantsMousePressed

    private void manageDeliveryManMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDeliveryManMousePressed
        Delivery();
    }//GEN-LAST:event_manageDeliveryManMousePressed
   private void Delivery() {
        // TODO add your handling code here:
        manageDeliveryMan.setBackground(new Color(255,255,255));
        manageCustomerPanel.setBackground(new Color(0,0,0));
        manageRestaurants.setBackground(new Color(0,0,0));
        userinterface.SystemAdminWorkArea.Delivery Delivery = new userinterface.SystemAdminWorkArea.Delivery(SystemAdminPanelRight, ecosystem);
        SystemAdminPanelRight.add("Delivery",Delivery);
        CardLayout layout = (CardLayout) SystemAdminPanelRight.getLayout();
        layout.next(SystemAdminPanelRight);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SystemAdminPanelRight;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel manageCustomerPanel;
    private javax.swing.JLabel manageCustomers;
    private javax.swing.JPanel manageDeliveryMan;
    private javax.swing.JPanel manageRestaurants;
    private javax.swing.JPanel systemAdminPanel;
    // End of variables declaration//GEN-END:variables
}
