/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import java.util.regex.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author namir
 */
public class createPanel extends javax.swing.JPanel {

    /**
     * Creates new form createPanel
     */
    Product product;
    public createPanel(Product product) {
        initComponents();
         this.product = product;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        submit_button1 = new javax.swing.JButton();
        name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        contactno_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        medical_txt = new javax.swing.JTextField();
        ipadd_txt = new javax.swing.JTextField();
        selectimage_button1 = new javax.swing.JButton();
        labelPhoto1 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ssn_txt = new javax.swing.JTextField();
        health_txt = new javax.swing.JTextField();
        bank_txt = new javax.swing.JTextField();
        license_txt = new javax.swing.JTextField();
        vehicle_txt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        device_txt = new javax.swing.JTextField();
        linkedin_txt = new javax.swing.JTextField();

        jLabel28.setText("LICENSE NO:");

        jLabel29.setText("VEHICLE NO:");

        jLabel30.setText("DEVICE IDENTIFIER NO:");

        submit_button1.setText("SUBMIT");
        submit_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_button1submit_buttonActionPerformed(evt);
            }
        });

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtjTeextField1ActionPerformed(evt);
            }
        });
        name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                name_txtKeyReleased(evt);
            }
        });

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtjTextField2ActionPerformed(evt);
            }
        });

        contactno_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactno_txtjTextField3ActionPerformed(evt);
            }
        });

        ipadd_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipadd_txtjTextField13ActionPerformed(evt);
            }
        });

        selectimage_button1.setText("SELECT IMAGE");
        selectimage_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectimage_button1selectimage_buttonActionPerformed(evt);
            }
        });

        labelPhoto1.setBackground(new java.awt.Color(255, 255, 255));
        labelPhoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPhoto1.setOpaque(true);

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/WhatsApp Image 2021-09-24 at 2.31.22 AM.jpeg"))); // NOI18N

        jScrollPane2.setViewportView(jEditorPane2);

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel18.setText("PROFILE  BUILDER");

        jLabel19.setText("NAME:");

        jLabel20.setText("ADDRESS:");

        jLabel21.setText("DOB:");

        jLabel22.setText("CONTACT NO:");

        jLabel23.setText("EMAIL ADDRESS:");

        jLabel24.setText("SSN:");

        jLabel25.setText("MEDICAL RECORD NO:");

        jLabel26.setText("HEALTH POLICY NO:");

        jLabel27.setText("BANK ACCOUNT NO:");

        license_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                license_txtActionPerformed(evt);
            }
        });

        jLabel32.setText("LinkedIn:");

        jLabel33.setText("IP ADDRESS:");

        device_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                device_txtjTextField11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(650, 650, 650)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(submit_button1)
                            .addComponent(selectimage_button1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(470, 470, 470)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel33)
                                        .addGap(62, 62, 62))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(address_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                                .addGap(96, 96, 96)
                                .addComponent(jLabel30)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ipadd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(device_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vehicle_txt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(contactno_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                        .addComponent(email_txt)
                                        .addComponent(ssn_txt)
                                        .addComponent(medical_txt)
                                        .addComponent(health_txt)
                                        .addComponent(bank_txt)
                                        .addComponent(license_txt, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(jLabel23)
                                .addComponent(jLabel24)
                                .addComponent(jLabel25)
                                .addComponent(jLabel26)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)
                                .addComponent(jLabel29)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(icon1)
                            .addGap(460, 460, 460)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(402, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30))
                            .addComponent(jLabel19))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(device_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(linkedin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel33))
                            .addComponent(ipadd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(labelPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(selectimage_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(150, 150, 150)
                .addComponent(submit_button1)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(2, 2, 2))
                                .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(contactno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel24))
                                .addComponent(ssn_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel25)
                                .addComponent(medical_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel26)
                                .addComponent(health_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(license_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel29)
                                .addComponent(vehicle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(icon1)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void device_txtjTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_device_txtjTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_device_txtjTextField11ActionPerformed

    private void selectimage_button1selectimage_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectimage_button1selectimage_buttonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jEditorPane2.setText(filename);
        Image getAbsolutePath=null;
        ImageIcon icon= new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(labelPhoto1.getWidth(), labelPhoto1.getHeight(), Image.SCALE_SMOOTH);
        labelPhoto1.setIcon(icon);
    }//GEN-LAST:event_selectimage_button1selectimage_buttonActionPerformed

    private void ipadd_txtjTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipadd_txtjTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipadd_txtjTextField13ActionPerformed

    private void contactno_txtjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactno_txtjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactno_txtjTextField3ActionPerformed

    private void name_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_txtKeyReleased
        // TODO add your handling code here:
        String nam = "^[a-zA-Z0-9]{5,30}$";
        Pattern namm= Pattern.compile(nam);
        Matcher match= namm.matcher(name_txt.getText());
        if(!match.matches())
        jLabel1.setText("!");
        else
        jLabel1.setText(null);

    }//GEN-LAST:event_name_txtKeyReleased

    private void name_txtjTeextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtjTeextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtjTeextField1ActionPerformed

    private void submit_button1submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_button1submit_buttonActionPerformed
        product.setName(name_txt.getText());
        product.setAddress(address_txt.getText());
        product.setDob(date.getDateFormatString());
        product.setContactNo(contactno_txt.getText());
        product.setEmail(email_txt.getText());
        product.setSsn(ssn_txt.getText());
        product.setMedicalRecordNo(medical_txt.getText());
        product.setHealthPolicyNo(health_txt.getText());
        product.setBankAccountNo(bank_txt.getText());
        product.setLicenseNo(license_txt.getText());
        product.setVehicleNo(vehicle_txt.getText());
        product.setDeviceNo(device_txt.getText());
        product.setLinkedIn(linkedin_txt.getText());
        product.setIPAddress(ipadd_txt.getText());
        product.setjEditorPane2(jEditorPane2.getText());
        product.setLabelPhoto1((ImageIcon) labelPhoto1.getIcon());

    }//GEN-LAST:event_submit_button1submit_buttonActionPerformed

    private void address_txtjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtjTextField2ActionPerformed

    private void license_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_license_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_license_txtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField bank_txt;
    private javax.swing.JTextField contactno_txt;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField device_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField health_txt;
    private javax.swing.JLabel icon1;
    private javax.swing.JTextField ipadd_txt;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPhoto1;
    private javax.swing.JTextField license_txt;
    private javax.swing.JTextField linkedin_txt;
    private javax.swing.JTextField medical_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton selectimage_button1;
    private javax.swing.JTextField ssn_txt;
    private javax.swing.JButton submit_button1;
    private javax.swing.JTextField vehicle_txt;
    // End of variables declaration//GEN-END:variables
}
