/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.util.regex.*;


/**
 *
 * @author namir
 */
public class panelCreate extends javax.swing.JPanel {
    boolean fl = false;

    /**
     * Creates new form panelCreate
     */
    Product product;
    public panelCreate(Product product) {
        initComponents();
        this.product= product;
        boolean fl= false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        medical_txt = new javax.swing.JTextField();
        ssn_txt = new javax.swing.JTextField();
        health_txt = new javax.swing.JTextField();
        bank_txt = new javax.swing.JTextField();
        license_txt = new javax.swing.JTextField();
        vehicle_txt = new javax.swing.JTextField();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        device_txt = new javax.swing.JTextField();
        linkedin_txt = new javax.swing.JTextField();
        jLabel91 = new javax.swing.JLabel();
        ipadd_txt = new javax.swing.JTextField();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        labelPhoto1 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        name_txt = new javax.swing.JTextField();
        address_txt = new javax.swing.JTextField();
        jLabel96 = new javax.swing.JLabel();
        contactno_txt = new javax.swing.JTextField();
        selectImage = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();

        jLabel83.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel83.setText("PROFILE  BUILDER");

        jLabel84.setText("NAME:");

        jLabel85.setText("ADDRESS:");

        jLabel86.setText("DOB:");

        jLabel87.setText("CONTACT NO:");

        jLabel88.setText("EMAIL ADDRESS:");

        jLabel89.setText("SSN:");

        jLabel90.setText("MEDICAL RECORD NO:");

        jLabel97.setText("LinkedIn:");

        jLabel98.setText("IP ADDRESS:");

        device_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                device_txtjTextField11ActionPerformed(evt);
            }
        });

        jLabel91.setText("HEALTH POLICY NO:");

        ipadd_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipadd_txtjTextField13ActionPerformed(evt);
            }
        });

        jLabel92.setText("BANK ACCOUNT NO:");

        jLabel93.setText("LICENSE NO:");

        labelPhoto1.setBackground(new java.awt.Color(255, 255, 255));
        labelPhoto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPhoto1.setOpaque(true);

        jLabel94.setText("VEHICLE NO:");

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/WhatsApp Image 2021-09-24 at 2.31.22 AM.jpeg"))); // NOI18N

        jLabel95.setText("DEVICE IDENTIFIER NO:");

        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtjTeextField1ActionPerformed(evt);
            }
        });

        address_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address_txtjTextField2ActionPerformed(evt);
            }
        });

        jLabel96.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        contactno_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactno_txtjTextField3ActionPerformed(evt);
            }
        });

        selectImage.setText("select image");
        selectImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectImageActionPerformed(evt);
            }
        });

        submitButton.setText("submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jEditorPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(516, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectImage)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addGap(9, 9, 9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(labelPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel96)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(icon1)
                            .addGap(460, 460, 460)
                            .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel85)
                                        .addGap(89, 89, 89)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(vehicle_txt)
                                                    .addComponent(license_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(bank_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(health_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(medical_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ssn_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(email_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(contactno_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(address_txt))
                                                .addGap(237, 237, 237))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(278, 278, 278))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel84)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel97)
                                            .addComponent(jLabel95)
                                            .addComponent(jLabel98))))
                                .addComponent(jLabel86)
                                .addComponent(jLabel87)
                                .addComponent(jLabel88)
                                .addComponent(jLabel89)
                                .addComponent(jLabel90)
                                .addComponent(jLabel91)
                                .addComponent(jLabel92)
                                .addComponent(jLabel93)
                                .addComponent(jLabel94))
                            .addGap(122, 122, 122)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(device_txt)
                                .addComponent(linkedin_txt)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ipadd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(selectImage)
                        .addGap(162, 162, 162))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(submitButton)
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(jLabel84)
                            .addGap(42, 42, 42)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel85)
                                        .addComponent(address_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel97)
                                        .addComponent(linkedin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel86))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(ipadd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel98)))))
                                .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel87)
                                        .addComponent(contactno_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(33, 33, 33)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel88)
                                        .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(45, 45, 45)
                                    .addComponent(jLabel89))
                                .addComponent(ssn_txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel90)
                                .addComponent(medical_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel91)
                                .addComponent(health_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel92)
                                .addComponent(bank_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(47, 47, 47)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel93)
                                .addComponent(license_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(51, 51, 51)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel94)
                                .addComponent(vehicle_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(icon1)
                                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel96)
                            .addGap(101, 101, 101)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel95)
                                .addComponent(device_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 180, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 180, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void device_txtjTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_device_txtjTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_device_txtjTextField11ActionPerformed

    private void ipadd_txtjTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipadd_txtjTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipadd_txtjTextField13ActionPerformed

    private void name_txtjTeextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtjTeextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtjTeextField1ActionPerformed

    private void address_txtjTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address_txtjTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address_txtjTextField2ActionPerformed

    private void contactno_txtjTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactno_txtjTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactno_txtjTextField3ActionPerformed

    private void selectImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectImageActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File file=chooser.getSelectedFile();
        String filename=file.getAbsolutePath();
        jEditorPane2.setText(filename);
        Image getAbsolutePath= null;
        ImageIcon icon= new ImageIcon(filename);
        Image image = icon.getImage().getScaledInstance(labelPhoto1.getHeight(),labelPhoto1.getWidth(), Image.SCALE_SMOOTH);
        labelPhoto1.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_selectImageActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
         product.setName(name_txt.getText());
        product.setAddress(address_txt.getText());
        product.setDob(date.getDateFormatString());
        product.setContactNo(contactno_txt.getText());
        product.setEmail(email_txt.getText());
        product.setSsn(ssn_txt.getText());
        product.setMedicalRecordNo(medical_txt.getText());
        product.setHealthPolicyNo(health_txt.getText());
        product.setBankAccountNo(bank_txt.getText());
        product.setLicenseNo(license_txt.getText());
        product.setVehicleNo(vehicle_txt.getText());
        product.setDeviceNo(device_txt.getText());
        product.setLinkedIn(linkedin_txt.getText());
        product.setIPAddress(ipadd_txt.getText());
        product.setjEditorPane2(jEditorPane2.getText());
        product.setLabelPhoto1((ImageIcon) labelPhoto1.getIcon());
        String contactR="(0/1)?[6-9][0-9]{9}";
        String emailR="^[\\w\\-]+(\\.[\\w\\-]+) *@([A-Za-z]{2,4}$";
        String ssnR="^\\d{3}-?\\d{2}-?\\d{4}$";
        
        if(date.getDateFormatString().isEmpty()==true)
        {
           date.setDateFormatString("Mandatory");
           
            
        }
        if(name_txt.getText().isEmpty()==true)
        {
            name_txt.setText("Mandatory field");
            fl= false;
       
        }
        else fl = true;
        
        if(address_txt.getText().isEmpty()==true)
        {
            address_txt.setText("Mandatory field");
            fl= false;
        }
        else fl= true;
        
        if(email_txt.getText().isEmpty()==true)
        {
            email_txt.setText("Mandatory field");
            fl= false;
       
        }
        else if(email_txt.getText().matches(emailR)!=true){
            email_txt.setText("not valid");
        }
        else fl = true;
        
        if(contactno_txt.getText().isEmpty()==true)
        {
            contactno_txt.setText("Mandatory field");
            fl= false;
       
        }
        else if(contactno_txt.getText().matches(contactR)!=true){
            contactno_txt.setText("not valid");
        }
        else fl = true;
        
        if(ssn_txt.getText().isEmpty()==true)
        {
            ssn_txt.setText("Mandatory field");
            fl= false;
       
        }
        else if(ssn_txt.getText().matches(ssnR)!=true){
            ssn_txt.setText("not valid");
        }
        else fl = true;
        
        if(health_txt.getText().isEmpty()==true)
        {
            health_txt.setText("Mandatory field");
            fl= false;
       
        }
        else fl = true;
        
        if(bank_txt.getText().isEmpty()==true)
        {
            bank_txt.setText("Mandatory field");
            fl= false;
       
        }
        else fl = true;
        
        if(license_txt.getText().isEmpty()==true)
        {
            license_txt.setText("Mandatory field");
            fl= false;
       
        }
        else fl = true;
        
        if(linkedin_txt.getText().isEmpty()==true)
        {
            linkedin_txt.setText("Mandatory field");
            fl= false;
       
        }
        else fl = true;
        
        
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_txt;
    private javax.swing.JTextField bank_txt;
    private javax.swing.JTextField contactno_txt;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField device_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JTextField health_txt;
    private javax.swing.JLabel icon1;
    private javax.swing.JTextField ipadd_txt;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPhoto1;
    private javax.swing.JTextField license_txt;
    private javax.swing.JTextField linkedin_txt;
    private javax.swing.JTextField medical_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton selectImage;
    private javax.swing.JTextField ssn_txt;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField vehicle_txt;
    // End of variables declaration//GEN-END:variables
}
