/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.productWithQty;
import Business.WorkQueue.orderWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namir
 */
public class orderDetailsJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem ecosystem;
    orderWorkRequest workRequest;
    double total = 0.0;
    private DefaultTableModel orderTable;
    private DeliveryManDirectory deliveryManDirectory;
    private int index = -1;

    
    public orderDetailsJPanel(JPanel userProcessContainer, EcoSystem ecosystem, UserAccount account, orderWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.account = account;
        this.workRequest = workRequest;
        orderTable = (DefaultTableModel) tblOrderDetails.getModel();
        deliveryManDirectory = ecosystem.getDeliveryManDirectory();
        populateDeliveryManList(deliveryManDirectory.getDeliveryManList());
        changeButtonText();
        setVisibleEditable();
        Show();
    }
        private void Show() {
        
        populateDeliveryMan();
        
        restaurantName.setText(workRequest.getRestaurant().getName());
        requestDate.setText(workRequest.getRequestDate().toString());
        status.setText(workRequest.getStatus());
        message.setText(workRequest.getMessage());

        orderTable.setRowCount(0);
        for (productWithQty productWithQuantity : workRequest.getProductssWithQtyList()) {
            Object[] row = new Object[orderTable.getColumnCount()];
            row[0] = productWithQuantity;
            row[1] = productWithQuantity.getQty();
            row[2] = productWithQuantity.getProduct().getpPrice() * productWithQuantity.getQty();
            total += productWithQuantity.getProduct().getpPrice() * productWithQuantity.getQty();
            orderTable.addRow(row);
        }
        totalPrice.setText(total + "");

    }

    private void populateDeliveryMan() {
        if(workRequest.getDeliverMan() == null &&  
                !("ordered".equalsIgnoreCase(workRequest.getStatus()) || "declined".equalsIgnoreCase(workRequest.getStatus()))){
            assignDeliveryPersonLabel.setVisible(true);
            assignDeliveryPerson.setVisible(true);
            addDeliveryPerson.setVisible(true);
            deliveryManNameValue.setVisible(false);
            deliveryManLabel.setVisible(false);
        }else{
            assignDeliveryPersonLabel.setVisible(false);
            assignDeliveryPerson.setVisible(false);
            addDeliveryPerson.setVisible(false);
            deliveryManNameValue.setVisible(true);
            deliveryManLabel.setVisible(true);
            if(workRequest.getDeliverMan() != null){
                deliveryManNameValue.setText(workRequest.getDeliverMan().getName());
            }else{
              deliveryManNameValue.setText("Not Assigned");  
            }
        }
    }
    
      public void populateDeliveryManList(ArrayList<DeliveryMan> deliveryManList) {
        if(workRequest.getDeliverMan() == null) {
            assignDeliveryPerson.setVisible(true);
             for (DeliveryMan deliveryMan : deliveryManList) {
                assignDeliveryPerson.addItem(deliveryMan.getName());
              }
        }else{
            assignDeliveryPerson.setVisible(false);
        } 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        deliveryManLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        restaurantName = new javax.swing.JLabel();
        deliveryManNameValue = new javax.swing.JLabel();
        requestDate = new javax.swing.JLabel();
        cartScrollPane1 = new javax.swing.JScrollPane();
        tblOrderDetails = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        acceptOrder = new javax.swing.JButton();
        assignDeliveryPerson = new javax.swing.JComboBox<>();
        assignDeliveryPersonLabel = new javax.swing.JLabel();
        addDeliveryPerson = new javax.swing.JButton();
        customerFeedBackPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerFeedbackField = new javax.swing.JTextArea();
        customerFeedbackLabel = new javax.swing.JLabel();
        declineOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Restaurant Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 130, -1));

        deliveryManLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        deliveryManLabel.setForeground(new java.awt.Color(51, 153, 0));
        deliveryManLabel.setText("Delivery Man Name");
        jPanel1.add(deliveryManLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 130, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Request Date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 117, -1));

        restaurantName.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        restaurantName.setForeground(new java.awt.Color(0, 153, 0));
        restaurantName.setText("mo");
        jPanel1.add(restaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 213, -1));

        deliveryManNameValue.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        deliveryManNameValue.setForeground(new java.awt.Color(51, 153, 0));
        deliveryManNameValue.setText("nam");
        jPanel1.add(deliveryManNameValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 186, -1));

        requestDate.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        requestDate.setForeground(new java.awt.Color(0, 153, 0));
        requestDate.setText("<value>");
        jPanel1.add(requestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 213, -1));

        tblOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Qty", "Item Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartScrollPane1.setViewportView(tblOrderDetails);

        jPanel1.add(cartScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 660, 190));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 0));
        jLabel10.setText("Message");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, -1, -1));

        totalPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(0, 153, 0));
        totalPrice.setText("<value>");
        jPanel1.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 127, -1));

        message.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(0, 153, 0));
        message.setText("<value>");
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, 190, -1));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ORDER DETAILS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 660, -1));

        jLabel14.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 0));
        jLabel14.setText("Status");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 103, -1));

        status.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        status.setForeground(new java.awt.Color(0, 153, 0));
        status.setText("<value>");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 213, -1));

        btnBack1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(51, 153, 0));
        btnBack1.setText("<Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 13, -1, -1));

        acceptOrder.setBackground(new java.awt.Color(0, 0, 0));
        acceptOrder.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        acceptOrder.setForeground(new java.awt.Color(0, 153, 0));
        acceptOrder.setText("Accept Order");
        acceptOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptOrderActionPerformed(evt);
            }
        });
        jPanel1.add(acceptOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        assignDeliveryPerson.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        assignDeliveryPerson.setForeground(new java.awt.Color(51, 153, 0));
        assignDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignDeliveryPersonActionPerformed(evt);
            }
        });
        jPanel1.add(assignDeliveryPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 137, -1));

        assignDeliveryPersonLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        assignDeliveryPersonLabel.setForeground(new java.awt.Color(51, 153, 0));
        assignDeliveryPersonLabel.setText("Assign Delivery Person");
        jPanel1.add(assignDeliveryPersonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        addDeliveryPerson.setBackground(new java.awt.Color(0, 0, 0));
        addDeliveryPerson.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        addDeliveryPerson.setForeground(new java.awt.Color(0, 153, 0));
        addDeliveryPerson.setText("Add");
        addDeliveryPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeliveryPersonActionPerformed(evt);
            }
        });
        jPanel1.add(addDeliveryPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        customerFeedBackPanel.setBackground(new java.awt.Color(0, 0, 0));
        customerFeedBackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerFeedbackField.setColumns(20);
        customerFeedbackField.setRows(5);
        jScrollPane1.setViewportView(customerFeedbackField);

        customerFeedBackPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 13, 520, 100));

        customerFeedbackLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        customerFeedbackLabel.setForeground(new java.awt.Color(51, 153, 0));
        customerFeedbackLabel.setText("Customer Feedback");
        customerFeedBackPanel.add(customerFeedbackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 136, -1));

        jPanel1.add(customerFeedBackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 544, 710, 130));

        declineOrder.setBackground(new java.awt.Color(0, 0, 0));
        declineOrder.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        declineOrder.setForeground(new java.awt.Color(0, 153, 0));
        declineOrder.setText("Decline Order");
        declineOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                declineOrderMousePressed(evt);
            }
        });
        jPanel1.add(declineOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 679));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        orderJPanel OrderJPanel = new orderJPanel(userProcessContainer,ecosystem, account);
        userProcessContainer.add("OrderJPanel", OrderJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void acceptOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptOrderActionPerformed
        // TODO add your handling code here:
        if (workRequest.getStatus().equals("Ordered")) {
            workRequest.setStatus("Preparing");
            JOptionPane.showMessageDialog(null, " Order Accepted Successfully!!, Please assign delivery person");
        }else if(workRequest.getStatus().equals("Preparing")){
            workRequest.setStatus("Prepared");
            if(workRequest.getDeliverMan() == null){
                JOptionPane.showMessageDialog(null, " Order Prepared Successfully!!, Please assign delivery person");
            }else{
                JOptionPane.showMessageDialog(null, "Hurray, Delivery person will pick up the order in few minutes !!!");
            }
        }else if (workRequest.getStatus().equalsIgnoreCase("delivered")){
            setVisibleEditable();
        }else{
            acceptOrder.setVisible(false);
        }
        changeButtonText();
        status.setText(workRequest.getStatus());

    }//GEN-LAST:event_acceptOrderActionPerformed

    private void assignDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignDeliveryPersonActionPerformed
        // TODO add your handling code here:
        index = assignDeliveryPerson.getSelectedIndex();
        //clear of the selected items

    }//GEN-LAST:event_assignDeliveryPersonActionPerformed

    private void addDeliveryPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeliveryPersonActionPerformed
        // TODO add your handling code here:
        if(index >= 0){
            DeliveryMan deliveryMan = deliveryManDirectory.getDeliveryManList().get(index);
            workRequest.setDeliverMan(deliveryMan);
            JOptionPane.showMessageDialog(null, "Delivery person assigned successfully!!!");
            populateDeliveryMan();
        }
    }//GEN-LAST:event_addDeliveryPersonActionPerformed

    private void declineOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_declineOrderMousePressed
        declineOrder();
    }//GEN-LAST:event_declineOrderMousePressed
    private void declineOrder(){
        workRequest.setStatus("Declined");
        JOptionPane.showMessageDialog(null, "You have just declined the order, we will notify it to the customer!!");
        changeButtonText();
        status.setText(workRequest.getStatus());
    }
    
    private void changeButtonText() {
        switch(workRequest.getStatus()){
            case "Ordered":
                  acceptOrder.setText("Accept order");
                  declineOrder.setVisible(true);
                  break;
            case "Preparing":
                  acceptOrder.setText("Ready for delivery");
                  declineOrder.setVisible(false);
                  break;
            default:
                declineOrder.setVisible(false);
                acceptOrder.setVisible(false);
        }
        populateDeliveryMan();
    }
    
      private void setVisibleEditable(){
        if(workRequest.getStatus().equalsIgnoreCase("delivered")){
            customerFeedBackPanel.setVisible(true);
            customerFeedbackField.setVisible(true);
            customerFeedbackField.setEditable(true);
            if(workRequest.getFeedbackbyCustomer() != null){
                customerFeedbackField.setText(workRequest.getFeedbackbyCustomer());
                customerFeedbackField.setEditable(false);
            }
        }else{
            customerFeedBackPanel.setVisible(false);
            customerFeedbackField.setVisible(false);
            customerFeedbackField.setEditable(false);
           
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptOrder;
    private javax.swing.JButton addDeliveryPerson;
    private javax.swing.JComboBox<String> assignDeliveryPerson;
    private javax.swing.JLabel assignDeliveryPersonLabel;
    private javax.swing.JButton btnBack1;
    private javax.swing.JScrollPane cartScrollPane1;
    private javax.swing.JPanel customerFeedBackPanel;
    private javax.swing.JTextArea customerFeedbackField;
    private javax.swing.JLabel customerFeedbackLabel;
    private javax.swing.JButton declineOrder;
    private javax.swing.JLabel deliveryManLabel;
    private javax.swing.JLabel deliveryManNameValue;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel requestDate;
    private javax.swing.JLabel restaurantName;
    private javax.swing.JLabel status;
    private javax.swing.JTable tblOrderDetails;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
