/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.productWithQty;
import Business.WorkQueue.orderWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namir
 */
public class OrderIDetailsJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    UserAccount account;
    EcoSystem ecosystem;
    orderWorkRequest workRequest;
    double total = 0.0;
    private DefaultTableModel cartTable;
    /**
     * Creates new form OrderIDetailsJPanel
     */
    public OrderIDetailsJPanel(JPanel userProcessContainer,EcoSystem ecosystem,UserAccount account, orderWorkRequest workRequest) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem = ecosystem;
        this.account=account;
        this.workRequest=workRequest;
        cartTable = (DefaultTableModel) tblCart.getModel();
        setVisibleEditable();
        Show();
    }
        private void Show(){
        restaurantName.setText(workRequest.getRestaurant().getName());
        if(workRequest.getDeliverMan()!= null){
            deliveryManName.setText(workRequest.getDeliverMan().getName());
        }else
            deliveryManName.setText("Not Assigned yet");
        
        requestDate.setText(workRequest.getRequestDate().toString());
        status.setText(workRequest.getStatus());
        message.setText(workRequest.getMessage());
        
        cartTable.setRowCount(0);   
        for (productWithQty itemWithQuantity : workRequest.getProductssWithQtyList()) {
            Object[] row = new Object[cartTable.getColumnCount()];
            row[0] = itemWithQuantity;
            row[1] = itemWithQuantity.getQty();
            row[2] = itemWithQuantity.getProduct().getpPrice() * itemWithQuantity.getQty();
            total += itemWithQuantity.getProduct().getpPrice() * itemWithQuantity.getQty();
            cartTable.addRow(row);
        }
         totalPrice.setText(total + "");
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        restaurantName = new javax.swing.JLabel();
        deliveryManName = new javax.swing.JLabel();
        requestDate = new javax.swing.JLabel();
        cartScrollPane = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        submitFeedbackButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        customerFeedBackPanel = new javax.swing.JPanel();
        customerFeedbackLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerFeedbackField = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Restaurant Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 86, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 0));
        jLabel2.setText("Delivery Man Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 120, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Request Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 154, 117, -1));

        restaurantName.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        restaurantName.setForeground(new java.awt.Color(51, 153, 0));
        restaurantName.setText("<value>");
        jPanel1.add(restaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 86, 207, -1));

        deliveryManName.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        deliveryManName.setForeground(new java.awt.Color(51, 153, 0));
        deliveryManName.setText("<value>");
        jPanel1.add(deliveryManName, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 120, 207, -1));

        requestDate.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        requestDate.setForeground(new java.awt.Color(51, 153, 0));
        requestDate.setText("<value>");
        jPanel1.add(requestDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 154, 207, -1));

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Qty", "Item Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cartScrollPane.setViewportView(tblCart);

        jPanel1.add(cartScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 234, 660, 190));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 153, 0));
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 450, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Message");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 450, -1, -1));

        totalPrice.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(51, 153, 0));
        totalPrice.setText("<value>");
        jPanel1.add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 450, 131, -1));

        message.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(51, 153, 0));
        message.setText("<value>");
        jPanel1.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 450, 265, -1));

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 153, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ORDER DETAILS");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 280, -1));

        submitFeedbackButton.setBackground(new java.awt.Color(255, 255, 255));
        submitFeedbackButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        submitFeedbackButton.setForeground(new java.awt.Color(51, 153, 0));
        submitFeedbackButton.setText("Submit Feedback");
        submitFeedbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFeedbackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitFeedbackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 614, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 153, 0));
        jLabel13.setText("Status");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 188, 103, -1));

        status.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        status.setForeground(new java.awt.Color(51, 153, 0));
        status.setText("<value>");
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 188, 207, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 153, 0));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 9, -1, -1));

        customerFeedBackPanel.setBackground(new java.awt.Color(0, 0, 0));
        customerFeedBackPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerFeedbackLabel.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        customerFeedbackLabel.setForeground(new java.awt.Color(51, 153, 0));
        customerFeedbackLabel.setText("Customer FeedBack");
        customerFeedBackPanel.add(customerFeedbackLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        customerFeedbackField.setColumns(20);
        customerFeedbackField.setRows(5);
        jScrollPane1.setViewportView(customerFeedbackField);

        customerFeedBackPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 570, 100));

        jPanel1.add(customerFeedBackPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 479, 750, 130));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 750));
    }// </editor-fold>//GEN-END:initComponents

    private void submitFeedbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFeedbackButtonActionPerformed
        String feedback = customerFeedbackField.getText().toString();
        if(!feedback.isEmpty()){
            workRequest.setFeedbackbyCustomer(feedback);
            setVisibleEditable();
        }
        JOptionPane.showMessageDialog(null, "Feedback Submitted Successfully !!!");
    }//GEN-LAST:event_submitFeedbackButtonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        OrderIStatusJPanel orderStatusJPanel = new OrderIStatusJPanel(userProcessContainer,ecosystem, account);
        userProcessContainer.add("OrderStatusJPanel", orderStatusJPanel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed
    private void setVisibleEditable(){
        if(workRequest.getStatus().equalsIgnoreCase("delivered")){
            customerFeedBackPanel.setVisible(true);
            customerFeedbackField.setVisible(true);
            customerFeedbackField.setEditable(true);
            if(workRequest.getFeedbackbyCustomer() != null){
                customerFeedbackField.setText(workRequest.getFeedbackbyCustomer());
                customerFeedbackField.setEditable(false);
                submitFeedbackButton.setVisible(false);
            }else{
                submitFeedbackButton.setVisible(true);
            }
        }else{
            customerFeedBackPanel.setVisible(false);
            customerFeedbackField.setVisible(false);
            customerFeedbackField.setEditable(false);
            submitFeedbackButton.setVisible(false);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane cartScrollPane;
    private javax.swing.JPanel customerFeedBackPanel;
    private javax.swing.JTextArea customerFeedbackField;
    private javax.swing.JLabel customerFeedbackLabel;
    private javax.swing.JLabel deliveryManName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel requestDate;
    private javax.swing.JLabel restaurantName;
    private javax.swing.JLabel status;
    private javax.swing.JButton submitFeedbackButton;
    private javax.swing.JTable tblCart;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
