/*
 * BrowseProducts.java
 *
 * Created on October 10, 2008, 9:10 AM
 */
package ui.CustomerRole;

import model.Product;
import model.Supplier;
import model.SupplierDirectory;
import ui.SupplierRole.ViewProductDetailJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.MOL;


/**
 *
 * @author Rushabh
 */
public class BrowseProductsJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    SupplierDirectory supplierDirectory;
    MOL mol;

    /** Creates new form BrowseProducts */
    public BrowseProductsJPanel(JPanel userProcessContainer, SupplierDirectory supplierDirectory, MOL mol) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.supplierDirectory = supplierDirectory;
        this.mol = mol;
        
        
        popolateCombo();
        populateProductTable();
        searchYS();
        searchSeats();
      
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblSupplier = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox();
        btnSearchProduct = new javax.swing.JButton();
        lblProductCatalogue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductCatalog = new javax.swing.JTable();
        lblItemsInCart = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtseats = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmaxseats = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtyearsearch = new com.toedter.calendar.JYearChooser();

        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(650, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2021-10-08 at 9.49.49 PM.jpeg"))); // NOI18N
        lblTitle.setText("Have A Wonderful Booking Experience!");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblTitle.setIconTextGap(20);
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 90, -1));

        lblSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplier.setText("Supplier:");
        add(lblSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 76, 30));

        cmbSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSupplierActionPerformed(evt);
            }
        });
        add(cmbSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 151, -1));

        btnSearchProduct.setBackground(new java.awt.Color(255, 255, 255));
        btnSearchProduct.setText("Search First Available CAB");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });
        add(btnSearchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, 30));

        lblProductCatalogue.setForeground(new java.awt.Color(255, 255, 255));
        lblProductCatalogue.setText("Cab Details:");
        add(lblProductCatalogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        tblProductCatalog.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        tblProductCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Product Id", "Price", "Avail", "Year MFG", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProductCatalog.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblProductCatalog);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 644, 110));

        lblItemsInCart.setForeground(new java.awt.Color(255, 255, 255));
        lblItemsInCart.setText("Select a Cab from above options");
        add(lblItemsInCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, 20));

        btnCheckOut.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCheckOut.setText("Confirm the Booking!!");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, 240, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cars MFG in above selected Year");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Year:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 266, -1, 10));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cars with above selected Seats");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 280, 30));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Min Seats:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        txtseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseatsActionPerformed(evt);
            }
        });
        add(txtseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 50, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Max Seats:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        txtmaxseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaxseatsActionPerformed(evt);
            }
        });
        add(txtmaxseats, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 50, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search Using FILTER");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uber.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 540, 290, 230));
        add(txtyearsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 70, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSupplierActionPerformed
        // TODO add your handling code here:
        populateProductTable();
    }//GEN-LAST:event_cmbSupplierActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
               JOptionPane.showMessageDialog(null, "Your Cab will reach soon!", "Info", JOptionPane.NO_OPTION);

    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed
        String n = "yes";
        populateProductTable( n);


        
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        int yearmfg = txtyearsearch.getYear();
        searchYS(yearmfg);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int seatss = Integer.parseInt(txtseats.getText());
        int maxseatss = Integer.parseInt(txtmaxseats.getText());
        searchSeats(seatss, maxseatss);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtmaxseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaxseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaxseatsActionPerformed

    private void txtseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseatsActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JComboBox cmbSupplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblItemsInCart;
    private javax.swing.JLabel lblProductCatalogue;
    private javax.swing.JLabel lblSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblProductCatalog;
    private javax.swing.JTextField txtmaxseats;
    private javax.swing.JTextField txtseats;
    private com.toedter.calendar.JYearChooser txtyearsearch;
    // End of variables declaration//GEN-END:variables

    private void popolateCombo() {
         cmbSupplier.removeAllItems();
        for(Supplier s : supplierDirectory.getSupplierlist()){
            cmbSupplier.addItem(s);
             
        }


    }

    private void populateProductTable() {
        
        Supplier selectedSupplier = (Supplier) cmbSupplier.getSelectedItem();
        
        if(selectedSupplier == null){
            return;
        }
         DefaultTableModel model = (DefaultTableModel) tblProductCatalog.getModel();
        model.setRowCount(0);

        for (Product p : selectedSupplier.getProductCatalog().getProductcatalog()) {
            Object row[] = new Object[6];
            row[0] = p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3] = p.getAvail();
            row[4] = p.getYearmfg();
            row[5] = p.getSeats();
            model.addRow(row);
        }


    }
    private void populateProductTable(String n) {
        
        
         DefaultTableModel model = (DefaultTableModel) tblProductCatalog.getModel();
        model.setRowCount(0);
        
        for( Supplier s: supplierDirectory.getSupplierlist()){

        for (Product p : s.getProductCatalog().getProductcatalog()) {
           if(p.getAvail().equalsIgnoreCase(n)){
        
            Object row[] = new Object[6];
            row[0] = p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3] = p.getAvail();
            row[4] = p.getYearmfg();
            row[5] = p.getSeats();
            model.addRow(row);
        }
        }


    }}

    private void searchYS(int yearmfg) {
         DefaultTableModel model = (DefaultTableModel) tblProductCatalog.getModel();
        model.setRowCount(0);
        
        for( Supplier s: supplierDirectory.getSupplierlist()){

        for (Product p : s.getProductCatalog().getProductcatalog()) {
           if(p.getYearmfg() == yearmfg){
        
            Object row[] = new Object[6];
            row[0] = p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3] = p.getAvail();
            row[4] = p.getYearmfg();
            row[5] = p.getSeats();
            model.addRow(row);
           }
        }


    }
       
    }

    private void searchYS() {
       
    }

    private void searchSeats(int seatss, int maxseatss) {
          DefaultTableModel model = (DefaultTableModel) tblProductCatalog.getModel();
        model.setRowCount(0);
        
        for( Supplier s: supplierDirectory.getSupplierlist()){

        for (Product p : s.getProductCatalog().getProductcatalog()) {
           if(p.getSeats() <= maxseatss && p.getSeats()>= seatss ){
        
            Object row[] = new Object[6];
            row[0] = p;
            row[1] = p.getModelNumber();
            row[2] = p.getPrice();
            row[3] = p.getAvail();
            row[4] = p.getYearmfg();
            row[5] = p.getSeats();
            model.addRow(row);
           }
        }


    }
    }
     private void searchSeats() {
    }
}
